#!/bin/sh
#
# Script that demos, command line args
#

echo "Total number of command line arguments are $#"
echo "$0 is script name"
echo "$1 is first argument"
echo "$2 is second argument"
echo "All of them are :- $* or $@"
